name: loadbalancer
on: workflow_dispatch

jobs:
  build-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          ref: main

      - name: installing python
        uses: actions/setup-python@v6 
        with:
          python-version: 'pypy3.10' 
        
          

      - name: get pem file
        run: |
          echo "${{secrets.vishal-key1}}" > key.pem
          chmod 400 key.pem
          


      - name: cp python
        run:
          scp -o StrictHostKeyChecking=no -i key.pem app.py ec2-user@13.201.38.96:/home/ec2-user/

      - name: cp requirements
        run:
          scp -o StrictHostKeyChecking=no -i key.pem requirements.txt ec2-user@13.201.38.96:/home/ec2-user/

      - name: run application
        run:
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@13.201.38.96 "cd /home/ec2-user && python3 -m venv virtualenv && source virtualenv/bin/activate && pip3 install -r requirements.txt && python3 app.py"
